<<<<<<< HEAD
[build]
builder = "nixpacks"

[deploy]
startCommand = "python main.py"

[environment]
TELEGRAM_BOT_TOKEN = "7831036263:AAHSisyLSr5bSwfJ2jGXasRfLcRluo2y5gk"
IOTEX_RPC_URL = "https://api.iotex.me/api/graphql"
CONFIRMATIONS = "3"
POLL_INTERVAL_SEC = "4"
TZ = "Africa/Lagos"
=======
[build]
builder = "nixpacks"

[deploy]
startCommand = "python main.py"

[environment]
TELEGRAM_BOT_TOKEN = "7831036263:AAHSisyLSr5bSwfJ2jGXasRfLcRluo2y5gk"
IOTEX_RPC_URL = "https://api.iotex.me/api/graphql"
CONFIRMATIONS = "3"
POLL_INTERVAL_SEC = "4"
TZ = "Africa/Lagos"
>>>>>>> 090a6372a7df9bcd68c05a3dc7be4a82e9bd21a9
